(begin
    (read godot_domain/commands.lisp)
    ;(read godot_domain/actions_models.lisp)
    (read godot_domain/state_functions.lisp)
    (read godot_domain/lambdas.lisp)
    ;(read godot_domain/test.lisp)
    (read godot_domain/jobshop_common.lisp)
    ;(read godot_domain/jobshop_greedy.lisp)
    (read godot_domain/jobshop_advanced.lisp)
    (read godot_domain/problems/ft06.lisp)
)