extern crate core;

pub mod contextcollection;
pub mod documentation;
pub mod function;
pub mod kindlvalue;
pub mod lasynchandler;
pub mod lcoreoperator;
pub mod lenv;
pub mod lfuture;
pub mod llambda;
pub mod lnumber;
pub mod lruntimeerror;
pub mod lswitch;
pub mod lvalue;
pub mod lvalues;
pub mod macros;
pub mod module;
pub mod purefonction;
