(begin
    (read domains/gripper/domain.lisp)
    ;(read domains/gripper/actions_test.lisp)
    (read domains/gripper/problems/problem_1.lisp)
    ;(set-select aries)
    (cp.start false)
    ;(sleep 0.5)
    (cp.new-task pick-and-drop b1 kitchen)
    ;(cp.plan)
    ;(sleep 2)
    (define h (async (cp.set-start 1 2.5)))
    (sleep 0.001)
    (cp.plan)
    ;(dump_trace)
    (exit 0)
)

