(begin
    (set-current-dir (concatenate (get-env-var "OMPAS_PATH") "/ompas-gobot-sim/"))
    (read planning_domain/base.lisp)
    (read planning_domain/lambdas.lisp)
    ;(read planning_domain/plan_model.lisp)
    (read planning_domain/plan_model_debug.lisp)
    (read planning_domain/problems/p1_debug.lisp)
    ;(new-timed-goal-task 0 test)
    ;(plan)
    ; (plan t_jobshop)
    ; (plan t_process_on_machine package0 machine2 1)
    ; (plan t_process machine2 package0 1)
    (plan test)
    ;(plan test_2)
    (exit 0)
)