(begin
    (read acting_domain/types.lisp)
    (read acting_domain/commands.lisp)
    ;(read godot_domain/actions_models.lisp)
    (read acting_domain/state_functions.lisp)
    (read acting_domain/lambdas.lisp)
    ;(read godot_domain/test.lisp)
    (read acting_domain/jobshop_common.lisp)
    ;(read godot_domain/jobshop_greedy.lisp)
    ;(read godot_domain/jobshop_advanced.lisp)
    (read acting_domain/jobshop_advanced_lrpt.lisp)
    ;(read acting_domain/problems/ft06.lisp)
    (read acting_domain/problems/j06.lisp)
    ;(set-select c-choice)
)