(begin
    (def-action pick '(?r robot))
    (def-action pick_package '(?r robot) '(?p package))
    (def-action place '(?r robot))
    (def-action do_move '(?r robot) '(?a float) '(?s float) '(?d float))
    (def-action navigate_to '(?r robot) '(?x float) '(?y float))
    (def-action navigate_to_cell '(?r robot) '(?cx int) '(?cy int))
    (def-action navigate_to_area '(?r robot) '(?area area))
    (def-action go_charge '(?r robot))
    (def-action do_rotation '(?r robot) '(?a float) '(?w float))
    (def-action face_belt '(?r robot) '(?b belt) '(?w float))
)