(begin
    (def-state-function robot.coordinates '(?r robot) '(?c (tuple int int)))
    (def-state-function robot.instance '(?r robot) '(?t symbol))
    (def-state-function robot.coordinates_tile '(?r robot) '(?c (tuple int int)))
    (def-state-function robot.battery '(?r robot) '(?b float))
    (def-state-function robot.velocity '(?r robot) '(?s (tuple float float)))
    (def-state-function robot.rotation_speed '(?r robot) '(?w float))
    (def-state-function robot.in_station '(?r robot) '(?b bool))
    (def-state-function robot.in_interact_areas '(?r robot) '(?ia (tlist interact_area)))
    (def-state-function machine.instance '(?m machine) '(?t symbol))
    (def-state-function machine.coordinates '(?m machine) '(?c (tuple int int)))
    (def-state-function machine.coordinates_tile '(?m machine) '(?ct (tuple int int)))
    (def-state-function machine.input_belt '(?m machine) '(?ib belt))
    (def-state-function machine.output_belt '(?m machine) '(?ob belt))
    (def-state-function machine.processes_list '(?m machine) '(?pl (tlist int)))
    (def-state-function machine.type '(?m machine) '(?mt symbol))
    (def-state-function machine.progress_rate '(?m machine) '(?pr float))
    (def-state-function package.instance '(?p package) '(?t symbol))
    (def-state-function package.location '(?p package) '(?l symbol))
    (def-state-function package.processes_list '(?p package) '(?pl (tlist (tuple int float))))
    (def-state-function belt.instance '(?b belt) '(?t symbol))
    (def-state-function belt.belt_type '(?b belt) '(?t symbol))
    (def-state-function belt.polygons '(?b belt) '(?p (tlist (tuple int int))))
    (def-state-function belt.cells '(?b belt) '(?c (tlist (tuple int int))))
    (def-state-function belt.interact_areas '(?b belt) '(?ia (tlist interact_area)))
    (def-state-function belt.packages_list '(?b belt) '(?pl (tlist package)))
    (def-state-function parking_area.instance '(?pa parking_area) '(?t symbol))
    (def-state-function parking_area.polygons '(?pa parking_area) '(?p (tlist (tuple int int))))
    (def-state-function parking_area.cells '(?pa parking_area) '(?c (tlist (tuple int int))))
    (def-state-function interact_area.instance '(?pa parking_area) '(?t symbol))
    (def-state-function interact_area.polygons '(?pa parking_area) '(?p (tlist (tuple int int))))
    (def-state-function interact_area.cells '(?pa parking_area) '(?c (tlist (tuple int int))))
    (def-state-function interact_area.belt '(?pa parking_area) '(?b belt))
)