(def-initial-state
 (map '(((instance room) (bedroom kitchen living_room no_place))
   ((instance ball) (b1 b2 b3 b4 no_ball))
   ((instance gripper) (left right))
   (at-robby bedroom)
   ((at b1) bedroom)
   ((at b2) bedroom)
   ((at b3) bedroom)
   ((at b4) bedroom)
   ((carry left) no_ball)
   ((carry right) no_ball))))